server.port: 15062

spring:
  profiles: prod
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://servet.mysql.yunstou.com:3306/vsprodb?Unicode=true&amp;characterEncoding=UTF-8
    username: root
    password: X315134.y
    jmx-enabled: true
    initialSize: 5
    maxActive: 100
    minIdle: 5
    maxIdle: 25
    maxAge: 3600000
    maxWait: 10000
    timeBetweenEvictionRunsMillis: 10000
    minEvictableIdleTimeMillis: 10000
    testWhileIdle: true
    testOnBorrow: true
    validationQuery: "SELECT 1"
    testOnReturn: false
  quartz-datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://servet.mysql.yunstou.com:3306/quartz?Unicode=true&amp;characterEncoding=UTF-8
    username: root
    password: X315134.y
    jmx-enabled: true
    initialSize: 5
    maxActive: 100
    minIdle: 5
    maxIdle: 25
    maxAge: 3600000
    maxWait: 10000
    timeBetweenEvictionRunsMillis: 10000
    minEvictableIdleTimeMillis: 10000
    testWhileIdle: true
    testOnBorrow: true
    validationQuery: "SELECT 1"
    testOnReturn: false

  application:
      name: quartz-cluster-node-first

## 该配置节点为独立的节点。这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/**/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.vpis.schedule.entity,com.vpis.common.entity  # 注意：对应实体类的路径

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
